name: Build Wheel, Release, Upload

on:
  workflow_call:
    inputs:
      project:
        description: 'Name of the project to build and release'
        default: 'PROJECT_NAME'
        required: true
        type: string
      c_extension:
        description: 'Whether the project has a C extension'
        default: false
        required: true
        type: boolean
      maintainer_github_username:
        description: GitHub username authorized to start GitHub/PyPI release'
        required: true
        type: string
      python_version:
        description: 'Python version to use. If not provided (or set to 0), will be detected from pyproject.toml'
        default: 0
        required: false
        type: number
      release_branch:
        description: 'Branch to release from. If not provided, will default to main'
        default: main
        required: false
        type: string
      pip_packages:
        description: 'packages to install via pip'
        default: ''
        required: false
        type: string
    secrets:
      PYPI_TOKEN:
        description: 'PyPI token'
        required: true
      PAT_TOKEN:
        description: 'GitHub Personal Access Token'
        required: true

jobs:
  check-tag-privilege:
    uses: ./.github/workflows/_check-tag-privilege.yml
    with:
      maintainer_github_username: ${{ inputs.maintainer_github_username }}

  check-pat-token-validity:
    uses: ./.github/workflows/_check-pat-token-validity.yml
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

  check-pypi-token-validity:
    uses: ./.github/workflows/_check-pypi-token-validity.yml
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

  get-python-version:
    needs: [check-tag-privilege, check-pat-token-validity, check-pypi-token-validity]
    uses: ./.github/workflows/_get-python-version-latest.yml
    with:
      python_version: ${{ inputs.python_version }}

  build-wheel:
    needs: [get-python-version]
    uses: ./.github/workflows/_build-wheel.yml
    with:
      project: ${{ inputs.project }}
      c_extension: ${{ inputs.c_extension }}
      # Convert from number to string
      latest_python_version: ${{ fromJSON(needs.get-python-version.outputs.latest_python_version) }}
      python_versions_json: ${{ needs.get-python-version.outputs.python_versions_json }}
      pip_packages: ${{ inputs.pip_packages }}